#!/usr/bin/env python3
"""Generate (and verify) the table of contents for the append-only ledgers.

GAP_ANALYSIS.md and specs/90-audit.md are append-only ledgers read by people
looking for the one pass that touched their file. An index that is
hand-maintained rots into a lie within a week, which is worse than no index,
so this writes one and `tests/test_specs_freshness.py` fails the build when it
would carry a link that does not resolve — the same generate-and-guard shape
`ci/spec_tables.py` already uses, and for the same reason.

Nothing here deletes or reorders a line of a ledger. It writes ONE block
between two marker comments and touches nothing else.

    python ci/doc_index.py            # verify (exit 1 with the fix command)
    python ci/doc_index.py --write    # rewrite the blocks

THE CONTRACT IS A LINK THAT WORKS. Three facts about the renderer (GitHub's,
verified against github-slugger's own test fixtures — see
`test_the_index_slugs_match_githubs_own_fixtures`) shape everything below:

  * Every `## ` line is its own heading. A soft wrap written as a second
    `## ` line is TWO headings to the renderer, so the index may GROUP the
    wrap for reading, but the link must be the FIRST line's anchor — the one
    the page actually has. The previous version joined both lines and slugged
    the join, which produced an anchor matching neither heading: every
    wrapped entry was a dead link.

  * Anchors drop punctuation (`§`, `—`, `:` ... — anything that is not a
    letter, mark, decimal digit, connector, `-` or space) and then map EVERY
    space to ONE hyphen with no collapsing. `Addendum — 2026` therefore
    anchors as `addendum--2026` — the double hyphen is the whole subtlety,
    and whitespace-collapsing got it wrong on nearly every row here.

  * Duplicates are numbered page-wide (`-1`, `-2`) across ALL heading
    levels: a `### ` heading still takes a number in the counter.

WHAT IS A WRAP CONTINUATION: a `## ` line whose immediately preceding LINE is
itself a `## ` line and whose own text starts lowercase. Measured on these
files 2026-09-26: the six true wraps are all adjacent pairs with no blank
line between the halves, while the two real sections that start with a
lowercase NAME (`## core/settings.py pays its §1a debt`, `## core/lifecycle.py
seam exists ...`) have a blank line above and were previously swallowed whole
into the section before them. Both failure directions now degrade safe: a
missed wrap becomes one extra row whose link works; a wrongly joined wrap
still links to the first half's real anchor.
"""
from __future__ import annotations

import pathlib
import re
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- INDEX:BEGIN — generated by ci/doc_index.py; edit the headings, not this -->"
END = "<!-- INDEX:END -->"

#: Only the ledgers big enough to need one. ACCEPTANCE.md is a checklist meant
#: to be read top to bottom, so an index there would be navigation for a
#: document that is already navigable.
TARGETS = ("GAP_ANALYSIS.md", "specs/90-audit.md")

_HEADING = re.compile(r"^(#{1,6}) (.*)$")
_FENCE = re.compile(r"^\s*```")


def heading_lines(text: str) -> list[tuple[int, int, str]]:
    """(line index, level, title) for every ATX heading outside a code fence.

    ALL levels, in file order — the exact set the renderer gives anchors to.
    A `### ` heading never becomes an index row, but it does take a number in
    the duplicate counter, so a row's anchor cannot be computed without it.
    """
    out: list[tuple[int, int, str]] = []
    in_code = False
    for i, line in enumerate(text.splitlines()):
        if _FENCE.match(line):
            in_code = not in_code
            continue
        if in_code:
            continue
        m = _HEADING.match(line)
        if m:
            out.append((i, len(m.group(1)), m.group(2).strip()))
    return out


def _slug(title: str) -> str:
    """GitHub's own anchor function (github-slugger's `slug()`).

    Lowercase; drop every character that is not a letter, mark, decimal
    digit, connector punctuation (`_`), `-` or a space — `§` and `—` go the
    way of `:` and `,`; then EVERY space becomes one hyphen, no collapsing.
    The fixtures that pin this live in the guard test, taken from
    github-slugger's own vectors, because "what GitHub does" is the contract
    and this function is only a transcription of it.
    """
    out = []
    for ch in title.strip().lower():
        if ch in " -":           # every space becomes a hyphen; '-' stays
            out.append("-")
            continue
        cat = unicodedata.category(ch)
        if cat == "Pc" or cat[0] == "L" or cat[0] == "M" or cat == "Nd":
            out.append(ch)
        # everything else — punctuation, symbols, controls — is dropped
    return "".join(out)


def anchors(text: str) -> list[tuple[int, int, str, str]]:
    """(line index, level, anchor, title) with the page-wide duplicate rule.

    First `Addendum` anchors `addendum`, the second `addendum-1`, and a LATER
    heading whose own slug lands on a taken anchor is bumped the same way
    (github-slugger resolves collisions by the final string, not by the
    base — `echo`, `echo`, `echo 1` anchors as echo, echo-1, echo-1-1).
    """
    found = heading_lines(text)
    numbered = number_anchors([t for _i, _lv, t in found])
    # strict: number_anchors returns one anchor per title by construction, and a
    # silent truncation here would drop a section from the index without a word.
    return [(i, lv, a, _t) for (i, lv, _t), a in zip(found, numbered, strict=True)]


def number_anchors(titles: list[str]) -> list[str]:
    """GitHub's duplicate rule over titles in document order.

    Split out of `anchors()` so `ci/link_check.py` — which counts headings the
    index does not publish (setext underlines, hand-written `{#id}`s) and so has
    to walk a different set of lines — numbers them with the SAME function
    rather than a second copy of the rule.
    """
    taken: set[str] = set()
    counts: dict[str, int] = {}
    out: list[str] = []
    for title in titles:
        base = _slug(title)
        n = counts.get(base, 0)
        cand = f"{base}-{n}" if n else base
        while cand in taken:
            n += 1
            cand = f"{base}-{n}"
        counts[base] = n + 1
        taken.add(cand)
        out.append(cand)
    return out


def headings(text: str) -> list[tuple[str, str]]:
    """(anchor, title) for the `##` index rows, in file order.

    The anchor is always a REAL one — the first line of a wrapped heading —
    and the title is the wrap read as its author wrote it, halves joined with
    the space the wrap took out. Continuations still consume their own
    duplicate numbers (they are headings to the renderer) via `anchors()`.
    """
    lines = text.splitlines()
    out: list[tuple[str, str]] = []
    for i, level, anchor, title in anchors(text):
        if level != 2:
            continue
        prev = lines[i - 1] if i else ""
        if out and prev.startswith("## ") and title[:1].islower():
            out[-1] = (out[-1][0], f"{out[-1][1]} {title}")
        else:
            out.append((anchor, title))
    return out


def block(text: str) -> str:
    rows = headings(text)
    lines = [BEGIN, "",
             f"_{len(rows)} sections. Newest first, oldest last — the files are "
             f"append-only._", ""]
    lines += [f"- [{t}](#{a})" for a, t in rows]
    lines += ["", END]
    return "\n".join(lines)


def current(text: str) -> str | None:
    """The index block already in the text, or None if there is not one."""
    if BEGIN not in text or END not in text:
        return None
    return text[text.index(BEGIN):text.index(END) + len(END)]


def render(text: str) -> str:
    """The file with its index block replaced (or inserted after the intro)."""
    new = block(text)
    if current(text) is not None:
        return text.replace(current(text), new, 1)
    # First insertion: after the H1 and the paragraph that follows it, so the
    # index lands under the file's own "what am I" sentence.
    lines = text.splitlines()
    at = 1
    while at < len(lines) and not lines[at].startswith("## "):
        at += 1
    head, tail = "\n".join(lines[:at]), "\n".join(lines[at:])
    return f"{head.rstrip()}\n\n{new}\n\n{tail}"


def main(argv: list[str]) -> int:
    write = "--write" in argv
    stale = []
    for rel in TARGETS:
        path = ROOT / rel
        if not path.exists():
            print(f"MISSING: {rel}")
            return 1
        text = path.read_text(encoding="utf-8")
        want = render(text)
        if text == want:
            print(f"  current  {rel}")
            continue
        if write:
            path.write_text(want, encoding="utf-8")
            print(f"  wrote    {rel}")
        else:
            stale.append(rel)
    if stale:
        print(f"STALE index in: {', '.join(stale)}")
        print("  the headings moved and the index did not; run:")
        print("    python ci/doc_index.py --write")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
